// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecouvrementAPI.Data;

#nullable disable

namespace RecouvrementAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RecouvrementAPI.Models.Agence", b =>
                {
                    b.Property<int>("IdAgence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_agence");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAgence"));

                    b.Property<string>("Adresse")
                        .HasColumnType("longtext")
                        .HasColumnName("adresse");

                    b.Property<string>("NomAgence")
                        .HasColumnType("longtext")
                        .HasColumnName("nom_agence");

                    b.Property<string>("Ville")
                        .HasColumnType("longtext")
                        .HasColumnName("ville");

                    b.HasKey("IdAgence");

                    b.ToTable("agence");
                });

            modelBuilder.Entity("RecouvrementAPI.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_client");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdClient"));

                    b.Property<string>("Adresse")
                        .HasColumnType("longtext")
                        .HasColumnName("adresse");

                    b.Property<string>("CIN")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cin");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<int>("IdAgence")
                        .HasColumnType("int")
                        .HasColumnName("id_agence");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("prenom");

                    b.Property<string>("Statut")
                        .HasColumnType("longtext")
                        .HasColumnName("statut");

                    b.Property<string>("Telephone")
                        .HasColumnType("longtext")
                        .HasColumnName("telephone");

                    b.Property<string>("TokenAcces")
                        .HasColumnType("longtext")
                        .HasColumnName("token_acces");

                    b.Property<DateTime?>("TokenExpiration")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("token_expiration");

                    b.HasKey("IdClient");

                    b.HasIndex("IdAgence");

                    b.ToTable("client");
                });

            modelBuilder.Entity("RecouvrementAPI.Models.Communication", b =>
                {
                    b.Property<int>("IdCommunication")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_communication");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCommunication"));

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_envoi");

                    b.Property<int>("IdDossier")
                        .HasColumnType("int")
                        .HasColumnName("id_dossier");

                    b.Property<int?>("IdRelance")
                        .HasColumnType("int")
                        .HasColumnName("id_relance");

                    b.Property<string>("Message")
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.Property<string>("Origine")
                        .HasColumnType("longtext")
                        .HasColumnName("origine");

                    b.HasKey("IdCommunication");

                    b.HasIndex("IdDossier");

                    b.HasIndex("IdRelance");

                    b.ToTable("communication");
                });

            modelBuilder.Entity("RecouvrementAPI.Models.DossierRecouvrement", b =>
                {
                    b.Property<int>("IdDossier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_dossier");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDossier"));

                    b.Property<int>("ConfianceClient")
                        .HasColumnType("int")
                        .HasColumnName("confiance_client");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_creation");

                    b.Property<decimal>("FraisDossier")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("frais_dossier");

                    b.Property<int>("IdClient")
                        .HasColumnType("int")
                        .HasColumnName("id_client");

                    b.Property<decimal>("MontantImpaye")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("montant_impaye");

                    b.Property<decimal>("MontantInitial")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("montant_initial");

                    b.Property<string>("StatutDossier")
                        .HasColumnType("longtext")
                        .HasColumnName("statut_dossier");

                    b.Property<decimal>("TauxInteret")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("taux_interet");

                    b.Property<string>("TypeEmprunt")
                        .HasColumnType("longtext")
                        .HasColumnName("type_emprunt");

                    b.HasKey("IdDossier");

                    b.HasIndex("IdClient");

                    b.ToTable("dossier_recouvrement");
                });

            modelBuilder.Entity("RecouvrementAPI.Models.Echeance", b =>
                {
                    b.Property<int>("IdEcheance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_echeance");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEcheance"));

                    b.Property<DateTime>("DateEcheance")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_echeance");

                    b.Property<int>("IdDossier")
                        .HasColumnType("int")
                        .HasColumnName("id_dossier");

                    b.Property<decimal>("MontantDu")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("montant_du");

                    b.Property<decimal>("MontantPaye")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("montant_paye");

                    b.Property<int>("NombreJoursRetard")
                        .HasColumnType("int")
                        .HasColumnName("nombre_jours_retard");

                    b.Property<string>("Statut")
                        .HasColumnType("longtext")
                        .HasColumnName("statut");

                    b.HasKey("IdEcheance");

                    b.HasIndex("IdDossier");

                    b.ToTable("echeance");
                });

            modelBuilder.Entity("RecouvrementAPI.Models.Garantie", b =>
                {
                    b.Property<int>("IdGarantie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_garantie");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdGarantie"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int>("IdDossier")
                        .HasColumnType("int")
                        .HasColumnName("id_dossier");

                    b.Property<string>("TypeGarantie")
                        .HasColumnType("longtext")
                        .HasColumnName("type_garantie");

                    b.HasKey("IdGarantie");

                    b.HasIndex("IdDossier");

                    b.ToTable("garantie");
                });

            modelBuilder.Entity("RecouvrementAPI.Models.HistoriqueAction", b =>
                {
                    b.Property<int>("IdAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_action");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAction"));

                    b.Property<string>("Acteur")
                        .HasColumnType("longtext")
                        .HasColumnName("acteur");

                    b.Property<string>("ActionDetail")
                        .HasColumnType("longtext")
                        .HasColumnName("action_detail");

                    b.Property<DateTime>("DateAction")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_action");

                    b.Property<int>("IdDossier")
                        .HasColumnType("int")
                        .HasColumnName("id_dossier");

                    b.HasKey("IdAction");

                    b.HasIndex("IdDossier");

                    b.ToTable("historique_action");
                });

            modelBuilder.Entity("RecouvrementAPI.Models.HistoriquePaiement", b =>
                {
                    b.Property<int>("IdPaiement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_paiement");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPaiement"));

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_paiement");

                    b.Property<int>("IdDossier")
                        .HasColumnType("int")
                        .HasColumnName("id_dossier");

                    b.Property<decimal>("MontantPaye")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("montant_paye");

                    b.Property<string>("TypePaiement")
                        .HasColumnType("longtext")
                        .HasColumnName("type_paiement");

                    b.HasKey("IdPaiement");

                    b.HasIndex("IdDossier");

                    b.ToTable("historique_paiement");
                });

            modelBuilder.Entity("RecouvrementAPI.Models.IntentionClient", b =>
                {
                    b.Property<int>("IdIntention")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_intention");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdIntention"));

                    b.Property<int?>("ConfianceClient")
                        .HasColumnType("int")
                        .HasColumnName("confiance_client");

                    b.Property<DateTime>("DateIntention")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_intention");

                    b.Property<DateTime?>("DatePaiementPrevue")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_paiement_prevue");

                    b.Property<int>("IdDossier")
                        .HasColumnType("int")
                        .HasColumnName("id_dossier");

                    b.Property<decimal?>("MontantPropose")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("montant_propose");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("statut");

                    b.Property<string>("TypeIntention")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type_intention");

                    b.HasKey("IdIntention");

                    b.HasIndex("IdDossier");

                    b.ToTable("intention_client");
                });

            modelBuilder.Entity("RecouvrementAPI.Models.RelanceClient", b =>
                {
                    b.Property<int>("IdRelance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_relance");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRelance"));

                    b.Property<string>("Contenu")
                        .HasColumnType("longtext")
                        .HasColumnName("contenu");

                    b.Property<DateTime>("DateRelance")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_relance");

                    b.Property<int>("IdDossier")
                        .HasColumnType("int")
                        .HasColumnName("id_dossier");

                    b.Property<string>("Moyen")
                        .HasColumnType("longtext")
                        .HasColumnName("moyen");

                    b.Property<string>("Statut")
                        .HasColumnType("longtext")
                        .HasColumnName("statut");

                    b.HasKey("IdRelance");

                    b.HasIndex("IdDossier");

                    b.ToTable("relance_client");
                });

            modelBuilder.Entity("RecouvrementAPI.Models.ScoreRisque", b =>
                {
                    b.Property<int>("IdScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_score");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdScore"));

                    b.Property<DateTime>("DateCalcul")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_calcul");

                    b.Property<int>("IdDossier")
                        .HasColumnType("int")
                        .HasColumnName("id_dossier");

                    b.Property<string>("Niveau")
                        .HasColumnType("longtext")
                        .HasColumnName("niveau");

                    b.Property<int>("PointsGarantie")
                        .HasColumnType("int")
                        .HasColumnName("points_garantie");

                    b.Property<int>("PointsHistorique")
                        .HasColumnType("int")
                        .HasColumnName("points_historique");

                    b.Property<int>("PointsIntention")
                        .HasColumnType("int")
                        .HasColumnName("points_intention");

                    b.Property<int>("PointsRetard")
                        .HasColumnType("int")
                        .HasColumnName("points_retard");

                    b.Property<string>("Recommandation")
                        .HasColumnType("longtext")
                        .HasColumnName("recommandation");

                    b.Property<decimal>("Valeur")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valeur");

                    b.HasKey("IdScore");

                    b.HasIndex("IdDossier");

                    b.ToTable("score_risque");
                });

            modelBuilder.Entity("RecouvrementAPI.Models.UtilisateurBack", b =>
                {
                    b.Property<int>("IdAgent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_agent");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAgent"));

                    b.Property<DateTime?>("DerniereConnexion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("derniere_connexion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<int?>("IdAgence")
                        .HasColumnType("int")
                        .HasColumnName("id_agence");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mot_de_passe");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("prenom");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role");

                    b.Property<string>("Statut")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("statut");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telephone");

                    b.HasKey("IdAgent");

                    b.HasIndex("IdAgence");

                    b.ToTable("utilisateur_back");
                });

            modelBuilder.Entity("RecouvrementAPI.Models.Client", b =>
                {
                    b.HasOne("RecouvrementAPI.Models.Agence", "Agence")
                        .WithMany("Clients")
                        .HasForeignKey("IdAgence")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agence");
                });

            modelBuilder.Entity("RecouvrementAPI.Models.Communication", b =>
                {
                    b.HasOne("RecouvrementAPI.Models.DossierRecouvrement", "Dossier")
                        .WithMany("Communications")
                        .HasForeignKey("IdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecouvrementAPI.Models.RelanceClient", "Relance")
                        .WithMany("Communications")
                        .HasForeignKey("IdRelance");

                    b.Navigation("Dossier");

                    b.Navigation("Relance");
                });

            modelBuilder.Entity("RecouvrementAPI.Models.DossierRecouvrement", b =>
                {
                    b.HasOne("RecouvrementAPI.Models.Client", "Client")
                        .WithMany("Dossiers")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("RecouvrementAPI.Models.Echeance", b =>
                {
                    b.HasOne("RecouvrementAPI.Models.DossierRecouvrement", "Dossier")
                        .WithMany("Echeances")
                        .HasForeignKey("IdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("RecouvrementAPI.Models.Garantie", b =>
                {
                    b.HasOne("RecouvrementAPI.Models.DossierRecouvrement", "Dossier")
                        .WithMany("Garanties")
                        .HasForeignKey("IdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("RecouvrementAPI.Models.HistoriqueAction", b =>
                {
                    b.HasOne("RecouvrementAPI.Models.DossierRecouvrement", "Dossier")
                        .WithMany("HistoriqueActions")
                        .HasForeignKey("IdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("RecouvrementAPI.Models.HistoriquePaiement", b =>
                {
                    b.HasOne("RecouvrementAPI.Models.DossierRecouvrement", "Dossier")
                        .WithMany("HistoriquePaiements")
                        .HasForeignKey("IdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("RecouvrementAPI.Models.IntentionClient", b =>
                {
                    b.HasOne("RecouvrementAPI.Models.DossierRecouvrement", "Dossier")
                        .WithMany("Intentions")
                        .HasForeignKey("IdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("RecouvrementAPI.Models.RelanceClient", b =>
                {
                    b.HasOne("RecouvrementAPI.Models.DossierRecouvrement", "Dossier")
                        .WithMany("Relances")
                        .HasForeignKey("IdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("RecouvrementAPI.Models.ScoreRisque", b =>
                {
                    b.HasOne("RecouvrementAPI.Models.DossierRecouvrement", "Dossier")
                        .WithMany("ScoresRisque")
                        .HasForeignKey("IdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("RecouvrementAPI.Models.UtilisateurBack", b =>
                {
                    b.HasOne("RecouvrementAPI.Models.Agence", "Agence")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("IdAgence");

                    b.Navigation("Agence");
                });

            modelBuilder.Entity("RecouvrementAPI.Models.Agence", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("RecouvrementAPI.Models.Client", b =>
                {
                    b.Navigation("Dossiers");
                });

            modelBuilder.Entity("RecouvrementAPI.Models.DossierRecouvrement", b =>
                {
                    b.Navigation("Communications");

                    b.Navigation("Echeances");

                    b.Navigation("Garanties");

                    b.Navigation("HistoriqueActions");

                    b.Navigation("HistoriquePaiements");

                    b.Navigation("Intentions");

                    b.Navigation("Relances");

                    b.Navigation("ScoresRisque");
                });

            modelBuilder.Entity("RecouvrementAPI.Models.RelanceClient", b =>
                {
                    b.Navigation("Communications");
                });
#pragma warning restore 612, 618
        }
    }
}
